# Server properties
spring:
  jpa:
    #    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    consumer:
      auto-offset-reset: earliest

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRESS_URL}/test
    username: ${POSTGRESS_USERNAME}
    password: ${POSTGRESS_PASSWORD}

server:
  address: 0.0.0.0
  port: 8004

# Kafka properties
topic_user: telegram_user
topic_message: telegram_message
group_id: telegram
